//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfDrones.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameEngineMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameEngineMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameOfDrones.Engine.GameEngineMessages", typeof(GameEngineMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The move can&apos;t kill itself..
        /// </summary>
        internal static string AddKillMoveSameNameAssMoveError {
            get {
                return ResourceManager.GetString("AddKillMoveSameNameAssMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create game. The moves list is empty, and it should have at least one move..
        /// </summary>
        internal static string CreateGameEmptyMovesError {
            get {
                return ResourceManager.GetString("CreateGameEmptyMovesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create move. The move name can&apos;t be null or empty..
        /// </summary>
        internal static string CreateMoveEmptyNameError {
            get {
                return ResourceManager.GetString("CreateMoveEmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of max wins must be greater than zero..
        /// </summary>
        internal static string CreateRulesMaxWinsZeroError {
            get {
                return ResourceManager.GetString("CreateRulesMaxWinsZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game {0} can&apos;t be finished. Is not started..
        /// </summary>
        internal static string FinishGameNotStartedError {
            get {
                return ResourceManager.GetString("FinishGameNotStartedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game {0} doesn&apos;t exists..
        /// </summary>
        internal static string GameNotFoundError {
            get {
                return ResourceManager.GetString("GameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The move &apos;{0}&apos; already exists in the current rules..
        /// </summary>
        internal static string MoveAlreadyExitsError {
            get {
                return ResourceManager.GetString("MoveAlreadyExitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The move &apos;{0}&apos; doesn&apos;t exists..
        /// </summary>
        internal static string MoveNotFoundError {
            get {
                return ResourceManager.GetString("MoveNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the move can&apos;t be empty..
        /// </summary>
        internal static string PlayEmptyMoveNameError {
            get {
                return ResourceManager.GetString("PlayEmptyMoveNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player name can&apos;t be empty..
        /// </summary>
        internal static string PlayerNameEmptyError {
            get {
                return ResourceManager.GetString("PlayerNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game already has winner..
        /// </summary>
        internal static string PlayHasWinnerError {
            get {
                return ResourceManager.GetString("PlayHasWinnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PlayResult is not supported by this implementation of Game Of Drones..
        /// </summary>
        internal static string PlayResultNotSupported {
            get {
                return ResourceManager.GetString("PlayResultNotSupported", resourceCulture);
            }
        }
    }
}
